Amber/config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :medications

  resources :prescriptions

  resources :contacts

  resources :patients

  root 'patients#index' 
  

end

Amber/app/models/patient.rb
class Patient < ActiveRecord::Base
  # Relationships
  # -----------------------------
  has_many :contacts
  has_many :prescriptions
  has_many :medications, through: :prescriptions

  scope :alphabetical, -> { order('last_name, first_name') }

  def proper_name
    first_name + " " + last_name
  end
end

Amber/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :username, :password, :email, :phone, :active)
    end
end

Amber/app/helpers/patients_helper.rb
module PatientsHelper
end

Amber/app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Amber/app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to "Delete", @patient, method: :delete, data: { confirm: 'Are you sure you wish to delete your account?' } %> |
<%= link_to 'Back', patients_path %>

Amber/app/views/patients/index.html.erb
<html>
<head>
  <title>Amber</title>
  <%= favicon_link_tag 'favicon.ico' %>

</head>
<body>

<div class="banner">
  <div class="logo">
    <a href="/index.html">
    <img border="0" width="150px" src="assets/amber_light.svg">
    </a>
  </div>
  <ul id="menu">
    <a href="#"><li>ABOUT</li></a>
    <a href="#"><li>DASHBOARD</li></a>
  </ul>
  <div class="overlay" id="one">
    <center>
    <div class="title">What's really in your medicine?</div>
    <a onclick="indexTransition()" href="#">
    <div class="amber_button" style="margin-top:16px;">GET STARTED</div></a>
    </center>
  </div>
  <div class="overlay" id="two" style="background-color:#00bcd4;">
    Search for your medicine and compare ratings between different producers.
    <div style="margin-top:16px">

    <!-- SEARCH BOX - When submit the form, the view rendered will be the index view of our articles resource -->
<%= form_tag(medications_path, :method => "get", class: "navbar-form", id: "search-form") do %>
  <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", id: "searchbar", placeholder: "advil, acetaminophin, mylan..." %>
      <button class="btn" type="submit"><a onclick="" href="#"><div class="amber_button" style="margin-left:10px;">SEARCH</div></a></button>
      <% end %> 
      <br>
    </div>
    <hr>
    <a href="#" class="small_link">LOGIN /</a> 
    <a href="#" class="small_link">SIGN UP /</a>
    <a href="#" class="small_link">LEARN MORE</a>
  </div>

</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="assets/script.js"></script>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
</body>

</html>

<%-# commented out code with if false from here down -%>
<% if false %>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.email %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.active %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>
<% end %>

Amber/app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

Amber/app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>