Amber/config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :medications

  resources :prescriptions

  resources :contacts

  resources :patients

  root 'patients#index' 
  

end

Amber/app/models/prescription.rb
class Prescription < ActiveRecord::Base
  # Relationships
  # -----------------------------
  belongs_to :medication
  belongs_to :patient

  scope :chronological, -> { order('created_at') }	
end

Amber/app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @prescriptions = Prescription.all
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:patient_id, :dosage, :time, :active, :medication_id)
    end
end

Amber/app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

Amber/app/views/prescriptions/_form.html.erb
<%= form_for(@prescription) do |f| %>
  <% if @prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% @prescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Dosage" %><br>
    <%= f.text_field :dosage %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :medication_id %><br>
    <%= f.text_field :medication_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Amber/app/views/prescriptions/edit.html.erb
<h1>Editing prescription</h1>

<%= render 'form' %>

<%= link_to 'Show', @prescription %> |
<%= link_to "Delete", @medication, method: :delete, data: { confirm: 'Are you sure you wish to delete this medication?' } %> |
<%= link_to 'Back', prescriptions_path %>

Amber/app/views/prescriptions/index.html.erb
<h1>Listing prescriptions</h1>

<table>
  <thead>
    <tr>
      <th>Dosage</th>
      <th>Time</th>
      <th>Active</th>
      <th>Medication</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td><%= prescription.dosage %></td>
        <td><%= prescription.time %></td>
        <td><%= prescription.active %></td>
        <td><%= prescription.medication_id %></td>
        <td><%= link_to 'Show', prescription %></td>
        <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
        <td><%= link_to 'Delete', prescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_prescription_path %>

Amber/app/views/prescriptions/new.html.erb
<h1>New prescription</h1>

<%= render 'form' %>

<%= link_to 'Back', prescriptions_path %>

Amber/app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @prescription.patient_id %>
</p>

<p>
  <strong>Dosage:</strong>
  <%= @prescription.dosage %>
</p>

<p>
  <strong>Time:</strong>
  <%= @prescription.time %>
</p>

<p>
  <strong>Active:</strong>
  <%= @prescription.active %>
</p>

<p>
  <strong>Medication:</strong>
  <%= @prescription.medication_id %>
</p>

<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to "Delete", @prescription, method: :delete, data: { confirm: 'Are you sure you wish to delete this prescription?' } %> |
<%= link_to 'Back', prescriptions_path %>